version: '3'

tasks:
  build-k6:
    cmds:
      - xk6 build --with xk6-opentelemetry=. --with github.com/mostafa/xk6-kafka

  build-docker:
    cmds:
      - docker build -t xk6-opentelemetry .

  lint:
    cmds:
      - golangci-lint run

  testing-up:
    dir: ./testing
    cmds:
      - docker compose -p xk6-opentelemetry up -d

  testing-down:
    dir: ./testing
    cmds:
      - docker compose -p xk6-opentelemetry down

  run-examples:
    cmds:
      - ./k6 run examples/test-logs.js
      - ./k6 run examples/test-metrics.js
      - ./k6 run examples/test-metrics-histogram.js
      - ./k6 run examples/test-traces.js
