services:

  k6: 
    build: 
      context: . 
      dockerfile: ../Dockerfile
    image: localhost/xk6-opentelemetry:latest 
    restart: no 


  redpanda:
    image: redpandadata/redpanda:latest
    command: redpanda start --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false --kafka-addr INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092 --advertise-kafka-addr INSIDE://broker:29092,OUTSIDE://broker:9092
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    dns: 
      - 172.20.0.10
      
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - --config
      - /etc/otel/config.yaml
    volumes:
      - ./otel-collector.yaml/:/etc/otel/config.yaml
    restart: always
    depends_on:
      - redpanda 
    dns: 
      - 172.20.0.10
  
  metrics:
    image: localhost/xk6-opentelemetry:latest
    command:
      - run
      - /scripts/test-metrics.js
    volumes:
      - ../examples/:/scripts/  
    restart: always
    depends_on:
      - redpanda 
    dns: 
      - 172.20.0.10

  logs:
    image: localhost/xk6-opentelemetry:latest
    command:
      - run
      - /scripts/test-logs.js
    volumes:
      - ../examples/:/scripts/  
    restart: always
    depends_on:
      - redpanda 
    dns: 
      - 172.20.0.10


  traces:
    image: localhost/xk6-opentelemetry:latest
    command:
      - run
      - /scripts/test-traces.js
    volumes:
      - ../examples/:/scripts/  
    restart: always
    depends_on:
      - redpanda 
    dns: 
      - 172.20.0.10      
