services:

  k6: 
    build: 
      context: . 
      dockerfile: ../Dockerfile
    image: eftechcombr/xk6-opentelemetry:latest 
    restart: no 

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
    restart: always  
    dns: 
      - 172.20.0.10

      
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - --config
      - /etc/otel/config.yaml
    volumes:
      - ./otel-collector.yaml/:/etc/otel/config.yaml
    restart: always
    depends_on:
      - kafka 
    dns: 
      - 172.20.0.10
  
  metrics:
    image: localhost/xk6-opentelemetry:latest
    command:
      - run
      - /scripts/test-metrics.js
    volumes:
      - ../examples/:/scripts/  
    restart: always
    depends_on:
      - kafka 
    dns: 
      - 172.20.0.10

  logs:
    image: localhost/xk6-opentelemetry:latest
    command:
      - run
      - /scripts/test-logs.js
    volumes:
      - ../examples/:/scripts/  
    restart: always
    depends_on:
      - kafka 
    dns: 
      - 172.20.0.10


  traces:
    image: localhost/xk6-opentelemetry:latest
    command:
      - run
      - /scripts/test-traces.js
    volumes:
      - ../examples/:/scripts/  
    restart: always
    depends_on:
      - kafka 
    dns: 
      - 172.20.0.10      
